name: Performance Tests

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays at midnight UTC

jobs:
  performance-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-xdist

      - name: Run performance tests
        run: |
          python -m pytest tests/perf/test_query_limits.py -v -m perf
        env:
          KLAVIYO_API_KEY: ${{ secrets.KLAVIYO_API_KEY }}
          SUPERMETRICS_API_KEY: ${{ secrets.SUPERMETRICS_API_KEY }}

      - name: Upload performance results
        uses: actions/upload-artifact@v3
        with:
          name: performance-results
          path: |
            perf_results.csv
            perf_summary.csv

      - name: Check for performance regressions
        run: |
          if grep -q "FAILED" pytest-perf.log; then
            echo "Performance tests failed! Check the logs for details."
            exit 1
          fi
